### PR TITLE
Add cancel scredule shutdown notify

### PR DESCRIPTION
**Pull request by artem7902**

### CODE REVIEW

**Comment by williamparry** [comment]
Does this appear over a game when it's in fullscreen mode?

**Comment by artem7902** [comment]
Yes, I test it only with Dota2, but I think it also works with many other.

**Comment by williamparry** [comment]
Thanks for making this. There's a few things I'd like to change:

- Remove all AWS dependencies and use straight windows scheduling. We'll send SSM commands to it directly rather than use cloudwatchevents

- Change the program to not show a window, and can be called from Powershell with commands: ```cloudrigscheduler -shutdown <int>``` In minutes
```cloudrigscheduler -cancelshutdown```
```cloudrigscheduler -extendshutdown <int>``` In minutes
There'll only ever be one cloudrig shutdown scheduled task at a time, so the shutdown/cancelshutdown/extendshutdown can grab a list and use a prefixed name. The toast notification can then also call these commands.

- The program will be added to windows PATH using Powershell (during first cloudRIG creation) so that we can easily send messages

- Build a few tests to be able to each process locally without needing cloudRIG

**Comment by artem7902** [comment]
Add changes, please check it.

**Comment by artem7902** [comment]
@williamparry Hello, please check the last update and let me know.

**Comment by williamparry** [comment]
Hey, I'm looking at this now: I think you're missing PipeServer class?

**Comment by williamparry** [comment]
hey @artem7902 I've updated the code to do this with Powershell.

Appreciate your help - so go ahead and claim the bounty anyway :)

**Pull request closed without merging**
