### PR TITLE
Features/quick install emulators

### PR DESCRIPTION
**Pull request by artem7902**
It work's, but I'm not sure about UI. Please let me know if you want to change something :)

### CODE REVIEW

**Comment by williamparry** [comment]
I just made a bunch of changes - would you mind merging into them?

**Comment by artem7902** [comment]
@williamparry merged.

**Comment by williamparry** [comment]
I'll look at this eventually, but for now feel free to claim the bounty.

**Comment by williamparry** [comment]
i've decided against emulators for this project, but thank you for your work on it.

**Pull request closed without merging**
