### PR TITLE
Fix lambdas. Fix set drive script. Implement resize storage.

### PR DESCRIPTION
**Pull request by artem7902**
Now lambdas works, it fully tested. Fixed small bag with set drive script. Also add resize for volume. Auto delete old snapshot for ami.

### CODE REVIEW

**Comment by williamparry** [comment]
Cool. Could you pull in the changes I made yesterday and check they don't interfere with this PR?

**Comment by artem7902** [comment]
Ok, changed.

**Comment by williamparry** [comment]
i made some changes to the lambdas. Would be worth you pulling and taking a look.

**Comment by artem7902** [comment]
Looks good, thanks for code review.

**Pull request merged**
